# Analysis

```{r}
pacman::p_load(tidyverse, magrittr, here, yardstick)
main <- read_csv(here("data", "main.csv")) %>% select(fecha, ipc) %>% rowid_to_column(".row")
```

## 24 steps ahead forecasts plot

### Time series

```{r}
setwd(here("results"))
snaive <- read_csv("snaive_24_forecast.csv")
ar <- read_csv("ar_24_forecast.csv")
sarima <- read_csv("sarima_24_forecast.csv")
hw <- read_csv("hw_24_forecast.csv") %>% mutate(key = "holt-winters")
var <- read_csv("var_24_forecast.csv") 
setwd(here())
```

```{r}
ts_bind <- 
  list(snaive, ar, sarima, hw, var) %>% 
  reduce(bind_rows) %>% 
  pivot_wider(names_from = key, values_from = .pred)

ts_forecasts <- 
  main %>% 
  left_join(ts_bind %>% mutate(.row = 181:204)) %>% 
  select(-.row) %>% 
  filter(between(fecha, as.Date("2019-01-01"), as.Date("2021-12-01"))) %>% 
  pivot_longer(!fecha, names_to = "model", values_to = "value") %>% 
  arrange(model, fecha)
```

### Machine learning

```{r}
setwd(here("results"))
# knn <- read_csv("knn_24_forecast.csv") %>% mutate(key = "knn")
lstm <- read_csv("lstm_24_forecast.csv") %>% mutate(key = "lstm")
mlp <- read_csv("mlp_24_forecast.csv") %>% mutate(key = "mlp")
rf <- read_csv("rf_24_forecast.csv") %>% mutate(key = "rf")
svm <- read_csv("svm_24_forecast.csv") %>% mutate(key = "svm")
xgb <- read_csv("xgb_24_forecast.csv") %>% mutate(key = "xgb")
setwd(here())
```

```{r}
ml_bind <- 
  list(mlp, rf, svm, xgb) %>% 
  reduce(bind_rows) %>% 
  select(-ipc) %>% 
  pivot_wider(names_from = key, values_from = .pred) %>% 
  bind_cols(lstm %>% select("lstm" = .pred))

ml_forecasts <- 
  main %>% 
  left_join(ml_bind) %>% 
  select(-.row) %>% 
  filter(between(fecha, as.Date("2019-01-01"), as.Date("2021-12-01"))) %>% 
  pivot_longer(!fecha, names_to = "model", values_to = "value") %>% 
  arrange(model, fecha)
```

```{r}
ts_forecasts %>% write_csv(here("results", "analysis", "ts_24_forecasts.csv"))
ml_forecasts %>% write_csv(here("results", "analysis", "ml_24_forecasts.csv"))
```

## Weighted mean forecast

### Time series

```{r}
ipc <- 
  ts_forecasts %>% 
  drop_na() %>% 
  filter(model == "ipc" & between(fecha, as.Date("2020-01-01"), as.Date("2021-12-01"))) %>% 
  rename("ipc" = model, "truth" = value)

ts_models <- 
  ts_forecasts %>% 
  drop_na() %>% 
  filter(model != "ipc") %>% 
  rename("estimate" = value)

ts_ensamble <- 
  ts_models %>% 
  left_join(ipc) %>% 
  group_by(model, fecha) %>% 
  mutate(mae = mae_vec(truth = truth, estimate = estimate)) %>% 
  ungroup() %>% 
  select(fecha, model, estimate, mae) %>% 
  group_by(fecha) %>% 
  mutate(weigth = 1 - (mae / sum(mae))) %>% 
  summarise(`Modelos de series de tiempo` = weighted.mean(estimate, weigth))

ts_mean_forecasts <- 
  main %>% 
  left_join(ts_ensamble) %>% 
  select(-.row) %>% 
  filter(between(fecha, as.Date("2018-01-01"), as.Date("2021-12-01"))) %>% 
  pivot_longer(!fecha, names_to = "model", values_to = "value") %>% 
  arrange(model, fecha)
```

### Machine learning

```{r}
ipc <- 
  ml_forecasts %>% 
  drop_na() %>% 
  filter(model == "ipc" & between(fecha, as.Date("2020-01-01"), as.Date("2021-12-01"))) %>% 
  rename("ipc" = model, "truth" = value)

ml_models <- 
  ml_forecasts %>% 
  drop_na() %>% 
  filter(model != "ipc") %>% 
  rename("estimate" = value)

ml_ensamble <- 
  ml_models %>% 
  left_join(ipc) %>% 
  group_by(model, fecha) %>% 
  mutate(mae = mae_vec(truth = truth, estimate = estimate)) %>% 
  ungroup() %>% 
  select(fecha, model, estimate, mae) %>% 
  group_by(fecha) %>% 
  mutate(weigth = 1 - (mae / sum(mae))) %>% 
  summarise(`Modelos de aprendizaje estadístico` = weighted.mean(estimate, weigth))

ml_mean_forecasts <- 
  main %>% 
  left_join(ml_ensamble) %>% 
  select(-.row) %>% 
  filter(between(fecha, as.Date("2018-01-01"), as.Date("2021-12-01"))) %>% 
  pivot_longer(!fecha, names_to = "model", values_to = "value") %>% 
  arrange(model, fecha)
```

```{r}
ts_mean_forecasts %>% write_csv(here("results", "analysis", "ts_mean_forecasts.csv"))
ml_mean_forecasts %>% write_csv(here("results", "analysis", "ml_mean_forecasts.csv"))
```

## Table four: MAE and rMAE

```{r}
# snaïve
setwd(here("results"))
snaive_3_metrics <- read_csv("snaive_3_metrics.csv") %>% mutate(key = "snaive 3")
snaive_9_metrics <- read_csv("snaive_9_metrics.csv") %>% mutate(key = "snaive 9")
snaive_12_metrics <- read_csv("snaive_12_metrics.csv") %>% mutate(key = "snaive 12")
snaive_24_metrics <- read_csv("snaive_24_metrics.csv") %>% mutate(key = "snaive 24")
setwd(here())

snaive <- 
  list(snaive_3_metrics, snaive_9_metrics, snaive_12_metrics, snaive_24_metrics) %>%
  reduce(bind_rows) %>% 
  rename("metric" = .metric, "estimate" = .estimate) %>% 
  select(-.estimator) %>% 
  pivot_wider(names_from = key, values_from = estimate) %>% 
  mutate(key = "snaïve") %>% # Rename
  relocate(key) %>% 
  rename("h = 3" = 3, "h = 9" = 4, "h = 12" = 5, "h = 24" = 6)

# holt-winters
setwd(here("results"))
hw_3_metrics <- read_csv("hw_3_metrics.csv") %>% mutate(key = "holt-winters 3")
hw_9_metrics <- read_csv("hw_9_metrics.csv") %>% mutate(key = "holt-winters 9")
hw_12_metrics <- read_csv("hw_12_metrics.csv") %>% mutate(key = "holt-winters 12")
hw_24_metrics <- read_csv("hw_24_metrics.csv") %>% mutate(key = "holt-winters 24")
setwd(here())

hw <- 
  list(hw_3_metrics, hw_9_metrics, hw_12_metrics, hw_24_metrics) %>%
  reduce(bind_rows) %>% 
  rename("metric" = .metric, "estimate" = .estimate) %>% 
  select(-.estimator) %>% 
  pivot_wider(names_from = key, values_from = estimate) %>% 
  mutate(key = "holt-winters") %>% # Rename
  relocate(key) %>% 
  rename("h = 3" = 3, "h = 9" = 4, "h = 12" = 5, "h = 24" = 6)

# ar
setwd(here("results"))
ar_3_metrics <- read_csv("ar_3_metrics.csv") %>% mutate(key = "ar 3")
ar_9_metrics <- read_csv("ar_9_metrics.csv") %>% mutate(key = "ar 9")
ar_12_metrics <- read_csv("ar_12_metrics.csv") %>% mutate(key = "ar 12")
ar_24_metrics <- read_csv("ar_24_metrics.csv") %>% mutate(key = "ar 24")
setwd(here())

ar <- 
  list(ar_3_metrics, ar_9_metrics, ar_12_metrics, ar_24_metrics) %>%
  reduce(bind_rows) %>% 
  rename("metric" = .metric, "estimate" = .estimate) %>% 
  select(-.estimator) %>% 
  pivot_wider(names_from = key, values_from = estimate) %>% 
  mutate(key = "ar") %>% # Rename
  relocate(key) %>% 
  rename("h = 3" = 3, "h = 9" = 4, "h = 12" = 5, "h = 24" = 6)

# sarima
setwd(here("results"))
sarima_3_metrics <- read_csv("sarima_3_metrics.csv") %>% mutate(key = "sarima 3")
sarima_9_metrics <- read_csv("sarima_9_metrics.csv") %>% mutate(key = "sarima 9")
sarima_12_metrics <- read_csv("sarima_12_metrics.csv") %>% mutate(key = "sarima 12")
sarima_24_metrics <- read_csv("sarima_24_metrics.csv") %>% mutate(key = "sarima 24")
setwd(here())

sarima <- 
  list(sarima_3_metrics, sarima_9_metrics, sarima_12_metrics, sarima_24_metrics) %>%
  reduce(bind_rows) %>% 
  rename("metric" = .metric, "estimate" = .estimate) %>% 
  select(-.estimator) %>% 
  pivot_wider(names_from = key, values_from = estimate) %>% 
  mutate(key = "sarima") %>% # Rename
  relocate(key) %>% 
  rename("h = 3" = 3, "h = 9" = 4, "h = 12" = 5, "h = 24" = 6)

# var
setwd(here("results"))
var_3_metrics <- read_csv("var_3_metrics.csv") %>% mutate(key = "var 3")
var_9_metrics <- read_csv("var_9_metrics.csv") %>% mutate(key = "var 9")
var_12_metrics <- read_csv("var_12_metrics.csv") %>% mutate(key = "var 12")
var_24_metrics <- read_csv("var_24_metrics.csv") %>% mutate(key = "var 24")
setwd(here())

var <- 
  list(var_3_metrics, var_9_metrics, var_12_metrics, var_24_metrics) %>%
  reduce(bind_rows) %>% 
  rename("metric" = .metric, "estimate" = .estimate) %>% 
  select(-.estimator) %>% 
  pivot_wider(names_from = key, values_from = estimate) %>% 
  mutate(key = "var") %>% # Rename
  relocate(key) %>% 
  rename("h = 3" = 3, "h = 9" = 4, "h = 12" = 5, "h = 24" = 6)

# ensamble
setwd(here("results"))
ts_3_metrics <- read_csv("ts_3_metrics.csv") %>% mutate(key = "ts 3")
ts_9_metrics <- read_csv("ts_9_metrics.csv") %>% mutate(key = "ts 9")
ts_12_metrics <- read_csv("ts_12_metrics.csv") %>% mutate(key = "ts 12")
ts_24_metrics <- read_csv("ts_24_metrics.csv") %>% mutate(key = "ts 24")
setwd(here())

ts_ensemble <- 
  list(ts_3_metrics, ts_9_metrics, ts_12_metrics, ts_24_metrics) %>%
  reduce(bind_rows) %>% 
  rename("metric" = .metric, "estimate" = .estimate) %>% 
  select(-.estimator) %>% 
  pivot_wider(names_from = key, values_from = estimate) %>% 
  mutate(key = "ensemble (ts)") %>% # Rename
  relocate(key) %>% 
  rename("h = 3" = 3, "h = 9" = 4, "h = 12" = 5, "h = 24" = 6)
```

```{r}
# svm
setwd(here("results"))
svm_3_metrics <- read_csv("svm_3_metrics.csv") %>% mutate(key = "svm 3")
svm_9_metrics <- read_csv("svm_9_metrics.csv") %>% mutate(key = "svm 9")
svm_12_metrics <- read_csv("svm_12_metrics.csv") %>% mutate(key = "svm 12")
svm_24_metrics <- read_csv("svm_24_metrics.csv") %>% mutate(key = "svm 24")
setwd(here())

svm <- 
  list(svm_3_metrics, svm_9_metrics, svm_12_metrics, svm_24_metrics) %>%
  reduce(bind_rows) %>% 
  rename("metric" = .metric, "estimate" = .estimate) %>% 
  select(-.estimator, -.config) %>% 
  pivot_wider(names_from = key, values_from = estimate) %>% 
  mutate(key = "svm") %>% # Rename
  relocate(key) %>% 
  rename("h = 3" = 3, "h = 9" = 4, "h = 12" = 5, "h = 24" = 6)

# rf
setwd(here("results"))
rf_3_metrics <- read_csv("rf_3_metrics.csv") %>% mutate(key = "rf 3")
rf_9_metrics <- read_csv("rf_9_metrics.csv") %>% mutate(key = "rf 9")
rf_12_metrics <- read_csv("rf_12_metrics.csv") %>% mutate(key = "rf 12")
rf_24_metrics <- read_csv("rf_24_metrics.csv") %>% mutate(key = "rf 24")
setwd(here())

rf <- 
  list(rf_3_metrics, rf_9_metrics, rf_12_metrics, rf_24_metrics) %>%
  reduce(bind_rows) %>% 
  rename("metric" = .metric, "estimate" = .estimate) %>% 
  select(-.estimator, -.config) %>% 
  pivot_wider(names_from = key, values_from = estimate) %>% 
  mutate(key = "rf") %>% # Rename
  relocate(key) %>% 
  rename("h = 3" = 3, "h = 9" = 4, "h = 12" = 5, "h = 24" = 6)

# xgb
setwd(here("results"))
xgb_3_metrics <- read_csv("xgb_3_metrics.csv") %>% mutate(key = "xgb 3")
xgb_9_metrics <- read_csv("xgb_9_metrics.csv") %>% mutate(key = "xgb 9")
xgb_12_metrics <- read_csv("xgb_12_metrics.csv") %>% mutate(key = "xgb 12")
xgb_24_metrics <- read_csv("xgb_24_metrics.csv") %>% mutate(key = "xgb 24")
setwd(here())

xgb <- 
  list(xgb_3_metrics, xgb_9_metrics, xgb_12_metrics, xgb_24_metrics) %>%
  reduce(bind_rows) %>% 
  rename("metric" = .metric, "estimate" = .estimate) %>% 
  select(-.estimator, -.config) %>% 
  pivot_wider(names_from = key, values_from = estimate) %>% 
  mutate(key = "xgb") %>% # Rename
  relocate(key) %>% 
  rename("h = 3" = 3, "h = 9" = 4, "h = 12" = 5, "h = 24" = 6)

# mlp
setwd(here("results"))
mlp_3_metrics <- read_csv("mlp_3_metrics.csv") %>% mutate(key = "mlp 3")
mlp_9_metrics <- read_csv("mlp_9_metrics.csv") %>% mutate(key = "mlp 9")
mlp_12_metrics <- read_csv("mlp_12_metrics.csv") %>% mutate(key = "mlp 12")
mlp_24_metrics <- read_csv("mlp_24_metrics.csv") %>% mutate(key = "mlp 24")
setwd(here())

mlp <- 
  list(mlp_3_metrics, mlp_9_metrics, mlp_12_metrics, mlp_24_metrics) %>%
  reduce(bind_rows) %>% 
  rename("metric" = .metric, "estimate" = .estimate) %>% 
  select(-.estimator, -.config) %>% 
  pivot_wider(names_from = key, values_from = estimate) %>% 
  mutate(key = "mlp") %>% # Rename
  relocate(key) %>% 
  rename("h = 3" = 3, "h = 9" = 4, "h = 12" = 5, "h = 24" = 6)

# lstm
setwd(here("results"))
lstm_3_metrics <- read_csv("lstm_3_metrics.csv") %>% mutate(key = "lstm 3")
lstm_9_metrics <- read_csv("lstm_9_metrics.csv") %>% mutate(key = "lstm 9")
lstm_12_metrics <- read_csv("lstm_12_metrics.csv") %>% mutate(key = "lstm 12")
lstm_24_metrics <- read_csv("lstm_24_metrics.csv") %>% mutate(key = "lstm 24")
setwd(here())

lstm <- 
  list(lstm_3_metrics, lstm_9_metrics, lstm_12_metrics, lstm_24_metrics) %>%
  reduce(bind_rows) %>% 
  rename("metric" = .metric, "estimate" = .estimate) %>% 
  select(-.estimator) %>% 
  pivot_wider(names_from = key, values_from = estimate) %>% 
  mutate(key = "lstm") %>% # Rename
  relocate(key) %>% 
  rename("h = 3" = 3, "h = 9" = 4, "h = 12" = 5, "h = 24" = 6)

# ensemble
setwd(here("results"))
ml_3_metrics <- read_csv("ml_3_metrics.csv") %>% mutate(key = "ml 3")
ml_9_metrics <- read_csv("ml_9_metrics.csv") %>% mutate(key = "ml 9")
ml_12_metrics <- read_csv("ml_12_metrics.csv") %>% mutate(key = "ml 12")
ml_24_metrics <- read_csv("ml_24_metrics.csv") %>% mutate(key = "ml 24")
setwd(here())

ml_ensemble <- 
  list(ml_3_metrics, ml_9_metrics, ml_12_metrics, ml_24_metrics) %>%
  reduce(bind_rows) %>% 
  rename("metric" = .metric, "estimate" = .estimate) %>% 
  select(-.estimator) %>% 
  pivot_wider(names_from = key, values_from = estimate) %>% 
  mutate(key = "ensemble (ml)") %>% # Rename
  relocate(key) %>% 
  rename("h = 3" = 3, "h = 9" = 4, "h = 12" = 5, "h = 24" = 6)
```

```{r}
ts_metrics <- 
  snaive %>% 
  bind_rows(hw, ar, sarima, var, ts_ensemble)

ml_metrics <- 
  svm %>% 
  bind_rows(rf, xgb, mlp, lstm, ml_ensemble)
```

```{r}
snaive_longer <- 
  ts_metrics %>% 
  bind_rows(ml_metrics) %>% 
  filter(metric == "mae") %>% 
  select(-metric) %>% 
  pivot_longer(-key) %>% 
  filter(key == "snaïve")

models_longer <- 
  ts_metrics %>% 
  bind_rows(ml_metrics) %>% 
  filter(metric == "mae") %>% 
  select(-metric) %>% 
  pivot_longer(-key)

mae <- 
  ts_metrics %>% 
  bind_rows(ml_metrics) %>% 
  filter(metric == "mae") %>% 
  select(-metric)

rmae <- 
  models_longer %>% 
  left_join(snaive_longer, by = "name") %>% 
  rename("key" = key.x, "horizon" = name, "mae" = value.x, "naive" = value.y) %>% 
  select(-key.y) %>% 
  mutate(rmae = mae/naive) %>% 
  select(-naive, -mae) %>% 
  pivot_wider(names_from = horizon, values_from = rmae)
```

```{r}
mae %>% write_csv(here("results", "analysis", "final_mae.csv"))
rmae %>% write_csv(here("results", "analysis", "final_rmae.csv"))
```

## Table five: MASE

```{r}
ts_metrics %>% 
  bind_rows(ml_metrics) %>% 
  filter(metric == "mase") %>% 
  select(-metric) %>% 
  pivot_longer(-key) %>% 
  pivot_wider(names_from = key, values_from = value) %>% 
  write_csv(here("results", "analysis", "final_mase.csv"))
```
