---
bibliography: references.bib
---

# Conclusiones

Los hallazgos de esta investigación demuestran que modelos SARIMA y VAR exhiben el mejor desempeño en lo que respecta a pronósticos de 3 y 9 meses. Además, la regresión de vectores de soporte (SVR) y los algoritmos de bosques aleatorios (RF) y potenciación de gradiente extremo (XGB) son capaces de generar pronósticos altamente eficientes en horizontes de 12 y 24 meses. Por lo tanto, ambas categorías pueden verse como métodos complementarios durante tareas de predicción en diversos horizontes temporales.

En línea con los resultados que obtienen @ülke2018 y @parmezan2019, la regresión de vectores de soporte (SVR) se comporta como el método con mejor desempeño en de la categoría de *machine learning*. Mientras que, en línea con @rodríguez-vargas2020, la combinación de pronósticos de métodos de aprendizaje de máquina supera a la combinación de resultados de los modelos econométricos tradicionales en 3 de los 4 horizontes temporales evaluados (y obtiene los mismos resultados en el pronóstico de 3 meses hacia delante). Sin embargo, la naturaleza de los algoritmos de aprendizaje estadístico impide verificar la consistencia teórica de sus predicciones, por lo que pueden no ser apropiados en situaciones donde se requiera no solo predicción sino inferencia durante el análisis.

La principal contribución de este estudio es mostrar en qué medida los algoritmos de aprendizaje automático pueden ser considerados como herramientas relativamente útiles para generar, en el contexto de métodos no estructurales, pronósticos del ritmo inflacionario en Guatemala durante horizontes donde las acciones de política monetaria generan un impacto en la evolución del ritmo inflacionario interno.
