---
bibliography: references.bib
---

# Introducción

El artículo número 3 de la ley orgánica del Banco de Guatemala establece que su objetivo fundamental consiste en propiciar las condiciones monetarias, cambiarias y crediticias que promuevan la estabilidad en el nivel general de precios. En el 2005, como parte de su esfuerzo por lograr este fin, dicha entidad optó por conducir sus acciones a través de un esquema de metas inflacionarias.

Debido a que naturalmente existe un periodo de tiempo entre el ajuste de las condiciones en el mercado de dinero y el efecto que este cambio genera en las variables del sector real, la autoridad monetaria---bajo un régimen de metas explícitas de inflación---actúa en el presente considerando sus pronósticos sobre el comportamiento de los precios en el futuro.

Concretamente, un cambio en la tasa de interés de política monetaria puede demorar entre 12 y 24 meses en ejercer una influencia en la demanda agregada y, por tanto, en tener un impacto en la evolución del ritmo inflacionario interno. En consecuencia, el banco central deberá pronosticar esta última variable durante dicho horizonte temporal y efectuar sus decisiones de política monetaria de modo que pueda estar seguro de que los pronósticos y expectativas de inflación se mantendrán anclados a la meta establecida durante el mediano plazo [@moenjak2014a].

En este sentido, los pronósticos de variables macroeconómicas pueden llevarse a cabo por medio de dos enfoques distintos: Métodos estructurales y métodos no estructurales [@diebold1998]. Los primeros informan a la especificación de sus modelos a través de una teoría económica determinada, mientras que los últimos se valen de las correlaciones en forma reducida que subyacen en las series de tiempo, sin depender explícitamente de una teoría económica [@pratap2019].

Este estudio en particular se ocupará del segundo enfoque, que al mismo tiempo puede ser subdividido en dos metodologías diferentes. Por un lado se encuentran los métodos econométricos de series de tiempo, los cuales son considerados como modelos relativamente tradicionales, de los que sobresalen los modelos univariados autorregresivos integrados de medias móviles (ARIMA) y los modelos multivariados de vectores autorregresivos (VAR).

Por el otro, algoritmos de aprendizaje estadístico[^1] comienzan a ser cada vez más populares, principalmente por la creciente disponibilidad de grandes bases de datos y poder de cómputo, así como un mayor acceso a *software* especializado [@rodríguez-vargas2020], aunque---tal y como mencionan @coulombe2020---los métodos de aprendizaje de máquina en realidad tienen una historia dentro de la literatura macroeconométrica que se remonta a inicios de la década de los noventas.

[^1]: A lo largo de la presente investigación los términos "aprendizaje estadístico", "aprendizaje de máquina" y "aprendizaje automático" serán empleados indistintamente.

En general, al emplear modelos de series de tiempo, se asume que las variables utilizadas durante la estimación de los parámetros se vinculan entre sí a través de una dinámica intrínseca regida por relaciones lineales que únicamente conducen a soluciones que oscilan periódicamente o que exhiben un comportamiento exponencial, de modo que la totalidad en la conducta irregular del sistema es atribuida únicamente a una entrada que es tanto exógena como estocástica [@kantz2004nonlinear].

Sin embargo, esta entrada aleatoria puede no ser la fuente exclusiva de irregularidad. Evidencia apunta que tanto series macroeconómicas como datos financieros exhiben interesantes estructuras no-lineales que se originan debido al impacto de perturbaciones durante las fases del ciclo económico [@granger1993modeling; @lebaron1994].

Dada la posible naturaleza no-lineal entre la relación de las variables económicas, existe cada vez un mayor énfasis en la aplicación de modelos de aprendizaje automático, los cuales---a diferencia de sus contrapartes---son particularmente buenos para explotar este tipo de relaciones (así como interacciones de alto orden) durante el proceso de predicción de nuevos valores basados en los valores de sus regresores [@athey2019]. Precisamente, tal es el propósito del presente estudio.

Mediante una competencia de pronósticos fuera de muestra (*pseudo out-of-sample*) del ritmo inflacionario en Guatemala, esta investigación buscará evaluar si métodos de aprendizaje supervisado como regresión de vectores de soporte (SVR), bosques aleatorios (RF), algoritmos de potenciación de gradiente extremo (XGB), perceptrones multicapa (MLP) y redes neuronales recurrentes de larga memoria de corto plazo (LSTM) son capaces de generar pronósticos más eficientes---evaluados durante 4 horizontes temporales (3, 9, 12, y 24 meses) y comparados con la ayuda de 3 medidas de precisión (MAE, rMAE y MASE)---al contrastarlos con las predicciones de un repertorio de modelos estimados a partir de métodos econométricos tales como un modelo de camina aleatoria estacional (*snaïve*), un modelo de suavizamiento exponencial (*Holt-Winters*), un modelo autorregresivo (AR), uno autorregresivo integrado de medias móviles estacionales (SARIMA) y un modelo de vectores autorregresivos (VAR).

El resto del documento será organizado de la siguiente manera. La próxima sección hace un repaso de la literatura correspondiente al uso y evaluación de modelos paramétricos y no paramétricos en tareas de predicción para series de tiempo. La sección 3 se ocupa de presentar un resumen estadístico de la base de datos, la descripción y configuración computacional de los modelos empleados, además de la metodología de evaluación para las predicciones de los mismos. Por último, la sección 4 y 5 se enfocan en discutir los resultados y conclusiones del estudio, respectivamente.
