---
bibliography: references.bib
---

# Revisión de la literatura

Algunos autores afirman que la literatura dedicada a la comparación de pronósticos entre modelos econométricos y de aprendizaje de máquina es relativamente reciente. Por ejemplo, @rodríguez-vargas2020 observa que, si bien desde inicios de los años noventas ha habido diferentes estudios en los que variables como tasas de inflación y tipos de cambio son pronosticadas utilizando k-NN y redes neuronales, en ningún momento estos autores se enfocaron en producir evaluaciones de las propiedades de sus predicciones de manera sistemática.

No obstante, un análisis más detenido permite apreciar que ya desde esa década diversos estudios evalúan los resultados de pronósticos generados con redes neuronales artificiales al contrastarlos con las predicciones obtenidas por medio de modelos autorregresivos integrados de medias móviles y modelos de suavizamiento exponencial para series de tiempo en ámbitos micro y macroeconómicos.

@kang1991investigation encuentra que las predicciones de modelos ARIMA son iguales o superiores a las de 18 redes neuronales con arquitecturas diferentes. @foster1992 obtienen resultados similares: modelos de suavizamiento exponencial y de mínimos cuadrados ordinarios producen pronósticos más eficientes que redes neuronales en series de tiempo anuales y mensuales, aunque semejantes en series trimestrales. Mientras tanto, @hill1996 concluyen que los pronósticos generados por redes neuronales son comparables con las predicciones de modelos econométricos tradicionales para series anuales e incluso superiores en series mensuales y trimestrales.

Recientemente, @ülke2018 evalúan la eficiencia de 2 modelos de series de tiempo univariados (RW y AR), 2 multivariados (VAR y ARDL) y 3 modelos de aprendizaje estadístico (k-NN, ANN y SVR) en la predicción de tasas de inflación en Estados Unidos para el periodo de 1984 a 2014. Los autores pronostican dicha variable en 4 horizontes temporales (3, 6, 9 y 12 meses) y posteriormente comparan los resultados mediante la raíz del error cuadrático medio (RSME) y el coeficiente de determinación ($R^2$) de cada uno de los modelos. Los resultados les permiten concluir que la regresión de vectores de soporte (SVR) supera al resto de modelos al pronosticar el ritmo de inflación subyacente medido con el índice de precios de gastos de consumo personal (PCE), mientras que el modelo autorregresivo distribuido rezagado (ARDL) proporciona la mayor precisión en la predicción de la inflación subyacente medida a través del índice de precios al consumidor (CPI).

@makridakis2018 también contrastan la eficiencia de pronóstico entre 8 modelos de aprendizaje automático y 8 modelos estadísticos---utilizando un modelo de caminata aleatoria (RW) como punto de referencia---al generar predicciones para 3003 series que proceden de dominios micro y macroeconómicos. Los autores concluyen que los métodos econométricos tradicionales son más precisos que los de *machine learning.*

Sin embargo, @cerqueira2019 consideran que este último estudio se encuentra sesgado en lo que respecta al tamaño de muestra, debido a que la duración promedio de las series es de 116 observaciones. Curvas de aprendizaje elaboradas por medio de procedimientos precuenciales les permiten determinar que a medida que el tamaño de muestra se amplía, los pronósticos generados por modelos de aprendizaje de máquina superan en términos de eficiencia a los métodos tradicionales.

Por otra parte, @parmezan2019 realizan un meta-análisis de la literatura y concluyen que los 2 modelos más utilizados en 29 estudios que involucran métodos econométricos y de aprendizaje automático a lo largo de la última década son redes neuronales artificiales (ANN) y modelos ARIMA. Posteriormente, comparan 7 modelos estadísticos con 4 modelos de aprendizaje de máquina durante la predicción de 40 series temporales sintéticas y 55 series reales. Los resultados les permiten concluir que los modelos autorregresivos integrados de medias móviles estacionales (SARIMA), SVM y k-NN son los métodos más efectivos para el modelado y predicción de series de tiempo, respectivamente.

@katris2020 evalúa el desempeño de 3 modelos estadísticos (ARIMA, ARFIMA y ARFIMA/ GARCH) con relación a 3 modelos de aprendizaje de máquina (ANN, SVM y MARS) al pronosticar las tasas de desempleo mensual para 22 economías desarrolladas en 3 horizontes temporales distintos. El autor concluye que los modelos autorregresivos fraccionalmente integrados de medias móviles (ARFIMA) resultan ser los procedimientos más adecuados durante pronósticos de un paso hacia adelante (*one-step ahead*), mientras que, para el horizonte más largo (12 meses), redes neuronales logran resultados comparables con modelos ARFIMA. Puesto que ningún modelo es aceptado globamente (en términos de RMSE y MAE), el autor recomienda tener en cuenta tanto el horizonte de pronóstico como la ubicación geográfica de la serie durante la selección de un enfoque.

A nivel latinoamericano, @rodríguez-vargas2020 pronostica la tasa de variación interanual del índice de precios al consumidor en Costa Rica con cuatro modelos de aprendizaje estadístico (RF, k-NN, XGB y LSTM) y encuentra que los 2 modelos capaces de generar los pronósticos más eficientes son LSTM y k-NN. Además, el autor concluye que la combinación de pronósticos (a través del cómputo de un promedio de las predicciones) mejora el desempeño en todos los horizontes temporales. Sin embargo, el autor no compara los resultados obtenidos con las predicciones de modelos tradicionales.

@araujo2020machine, por otro lado, contrastan los pronósticos de la tasa de inflación en Brasil para 16 modelos distintos---de los que sobresalen ARMA y VAR en la categoría de modelos econométricos y bosques aleatorios (RF) y modelos lineales generalizados (GLM) en la categoría de aprendizaje de máquina. Los autores encuentran que algunos algoritmos de aprendizaje automático superan consistentemente a los métodos tradicionales en términos de error cuadrático medio (MSE).

Por último, @peirano2021 evalúan los resultados de modelos SARIMA y LSTM durante la predicción del ritmo inflacionario mensual en Brasil, México, Chile, Colombia y Perú. Los autores concluyen que es posible alcanzar una mayor eficiencia en el pronóstico ensamblando ambos modelos (en lugar de solamente obtener un promedio de sus predicciones), por lo que proponen un modelo híbrido SARIMA-LSTM con el propósito de conservar los beneficios de SARIMA como un método lineal; capturando los fenómenos no-lineales por vía de una red neuronal recurrente con arquitectura LSTM. Sin embargo, observan los autores, el modelo propuesto mejora el desempeño en las predicciones únicamente en algunos casos.

En general, una revisión sistemática de la literatura permite apreciar que existen ciertas constantes en lo que respecta a la comparación de predicciones entre métodos paramétricos y no paramétricos. En primer lugar, no existe un consenso en relación a cuál es la metodología más adecuada para generar pronósticos. Al hablar de esto (citation) hacen una referencia al *no free lunch theorem.* Además,

Horizonte de pronósticos y ubicación geográfica.

Cantidad de observaciones en series para machine learning.

Pre-procesamiento.

Modelos híbridos.
