# Resultados

```{r include=FALSE}
pacman::p_load(tidyverse, kableExtra, magrittr, here, patchwork)
main <- read_csv(here("data", "main.csv")) %>% select(fecha, ipc) %>% rowid_to_column(".row")
```

\renewcommand{\arraystretch}{1}

```{=tex}
\begin{center}

\small

\textbf{Figura 2:} Pronósticos de 24 meses hacia delante

\end{center}
```
\vspace{-12mm}

```{r include=FALSE}
ts_forecasts <- read_csv(here("results", "analysis", "ts_24_forecasts.csv"))
ml_forecasts <- read_csv(here("results", "analysis", "ml_24_forecasts.csv"))
```

```{r include=FALSE}
p1 <- 
  ggplot(filter(ts_forecasts, model != "ipc"), aes(fecha, value, color = model)) +
  geom_line(aes(fecha, value, color = model)) +
  geom_line(data = filter(ts_forecasts, model == "ipc"), linetype = "dashed") +
  labs(title = "(a) Modelos de series de tiempo") +
  theme_bw() +
  theme(
        # X axis
        axis.title.x = element_blank(),
        axis.text.x = element_text(size = 12),
        # Y axis
        axis.title.y = element_blank(),
        axis.text.y = element_text(size = 12),
        # Title
        plot.title = element_text(hjust = 0.5, 
                                  margin = margin(0, 0, 0.7, 0, "cm")),
        # Panel
        panel.grid = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.background = element_rect(fill = "white"),
        # Legend
        legend.title = element_blank(),
        legend.text = element_text(size = 11),
        legend.position = "bottom",
        legend.justification = "center",
        legend.margin = margin(.5, 0, 0, 0, "cm")
    ) + 
    guides(colour = guide_legend(nrow = 1))
```

```{r include=FALSE}
p2 <- 
  ggplot(filter(ml_forecasts, model != "ipc"), aes(fecha, value, color = model)) +
  geom_line(aes(fecha, value, color = model)) +
  geom_line(data = filter(ml_forecasts, model == "ipc"), linetype = "dashed") +
  labs(title = "(b) Modelos de aprendizaje estadístico") +
  theme_bw() +
  theme(
        # X axis
        axis.title.x = element_blank(),
        axis.text.x = element_text(size = 12),
        # Y axis
        axis.title.y = element_blank(),
        axis.text.y = element_text(size = 12),
        # Title
        plot.title = element_text(hjust = 0.5, 
                                  margin = margin(0, 0, 0.7, 0, "cm")),
        # Panel
        panel.grid = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.background = element_rect(fill = "white"),
        # Legend
        legend.title = element_blank(),
        legend.text = element_text(size = 11),
        legend.position = "bottom",
        legend.justification = "center",
        legend.margin = margin(.5, 0, 0, 0, "cm")
    ) + 
    guides(colour = guide_legend(nrow = 1))
```

```{r fig_two, echo=FALSE, warning=FALSE, message=FALSE, fig.align = 'center', fig.dim = c(11.5, 4.7)}
p1 + p2
```

\vspace{-12mm}

```{r include=FALSE}
ts_mean_forecasts <- read_csv(here("results", "analysis", "ts_mean_forecasts.csv"))
ml_mean_forecasts <- read_csv(here("results", "analysis", "ml_mean_forecasts.csv"))
ensamble <- ts_mean_forecasts %>% bind_rows(ml_mean_forecasts %>% filter(model != "ipc"))
```

```{r fig_two_two, echo=FALSE, warning=FALSE, message=FALSE, fig.align = 'center', fig.dim = c(11.5, 4.2)}
ggplot(filter(ensamble, model != "ipc"), aes(fecha, value, color = model)) +
  geom_line(aes(fecha, value, color = model)) +
  geom_line(data = filter(ensamble, model == "ipc"), linetype = "dashed") +
  labs(title = "(c) Ensamble de modelos") +
  theme_bw() +
  theme(
        # X axis
        axis.title.x = element_blank(),
        axis.text.x = element_text(size = 12),
        # Y axis
        axis.title.y = element_blank(),
        axis.text.y = element_text(size = 12),
        # Title
        plot.title = element_text(hjust = 0.5, 
                                  margin = margin(0, 0, 0.7, 0, "cm")),
        # Panel
        panel.grid = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.background = element_rect(fill = "white"),
        # Legend
        legend.title = element_blank(),
        legend.text = element_text(size = 11),
        legend.position = "bottom",
        legend.justification = "center",
        legend.margin = margin(.5, 0, 0, 0, "cm")
    ) + 
    guides(colour = guide_legend(nrow = 1))
```

```{=tex}
\begin{center}

\small

\textbf{Cuadro 4:} MAE y rMAE por modelo y horizonte de pronóstico

\normalsize

\end{center}
```
\vspace{-2.7mm}

```{r include=FALSE}
mae <- read_csv(here("results", "analysis", "final_mae.csv"))
rmae <- read_csv(here("results", "analysis", "final_rmae.csv")) %>% 
  rename("h = 3 " = 2, "h = 9 " = 3, "h = 12 " = 4, "h = 24 " = 5)

results_one <- 
  mae %>% 
  left_join(rmae) %>% 
  mutate(across(where(is.numeric), ~ round(., 2))) %>% 
  rename(" " = 1)
```

```{r table_four, echo=FALSE}
kbl(results_one, 
    booktabs = T,
    align = c("lcccccccc")) %>%
  kable_styling(font_size = 9,
                full_width = T) %>% 
  add_header_above(c(" " = 1, "MAE" = 4, "rMAE" = 4), align = "l") %>%
  column_spec(1, width = "2.9cm") %>% 
  group_rows(start_row = 1, 
             end_row = 6, 
             latex_align = "l",
             latex_gap_space = "-0.25cm") %>% 
  row_spec(6, bold = TRUE) %>% 
  group_rows(start_row = 7, 
             end_row = 12, 
             latex_align = "l",
             latex_gap_space = "-0.10cm") %>% 
  row_spec(12, bold = TRUE)
```

```{=tex}
\begin{center}

\small

\textbf{Cuadro 5:} MASE por modelo y horizonte de pronóstico

\normalsize

\end{center}
```
\vspace{-2.7mm}

```{r include=FALSE}
mase <- read_csv(here("results", "analysis", "final_mase.csv")) %>% 
  mutate(across(where(is.numeric), ~ round(., 2))) %>%  
  rename(" " = name)
```

```{r table_five, echo=FALSE}
kbl(mase, 
    booktabs = T,
    align = c("lcccccccccc")) %>%
  kable_classic() %>% 
  add_header_above(c(" " = 1, "MASE" = 10), align = "l") %>%
  kable_styling(font_size = 9,
                full_width = T) %>% 
  column_spec(1, width = "1.5cm") %>% 
  column_spec(3, width = "1.9cm")
```

```{=tex}
\begin{center}

\small

\textbf{Figura 3:} MASE por modelo y horizonte de pronóstico

\end{center}
```
\vspace{-12mm}

```{r include=FALSE}
ranking_mase <- read_csv(here("results", "analysis", "ranking_mase.csv"))
```

```{r fig_three, echo=FALSE, warning=FALSE, message=FALSE, fig.align = 'center', fig.dim = c(11.5, 4.2)}
ranking_mase %>% 
  ggplot(aes(fct_inorder(key, id), estimate, fill = horizon)) +
  geom_col(position = "dodge2") +
  scale_fill_discrete(limits = c("h = 3", "h = 9", "h = 12", "h = 24")) +
  theme_bw() +
  theme(
        # X axis
        axis.title.x = element_blank(),
        axis.text.x = element_text(size = 12),
        # Y axis
        axis.title.y = element_blank(),
        axis.text.y = element_text(size = 12),
        # Title
        plot.title = element_text(hjust = 0.5, 
                                  margin = margin(0, 0, 0.7, 0, "cm")),
        # Panel
        panel.grid = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.background = element_rect(fill = "white"),
        # Legend
        legend.title = element_blank(),
        legend.text = element_text(size = 11),
        legend.position = "bottom",
        legend.justification = "center",
        legend.margin = margin(.5, 0, 0, 0, "cm")
    ) + 
    guides(colour = guide_legend(nrow = 1))
```

```{=tex}
\begin{center}

\small

\textbf{Figura 4:} Complejidad computacional y precisión de pronóstico

\end{center}
```
\vspace{-12mm}

```{r include=FALSE}
cc <- read_csv(here("results", "analysis", "cc.csv"))
```

```{r fig_four, echo=FALSE, warning=FALSE, message=FALSE, fig.align = 'center', fig.dim = c(11.5, 4.2)}
cc %>% 
  ggplot(aes(cc, mae, label = key)) +
  geom_smooth(method = "lm", colour = "black", fill = "gray80") +
  geom_label() +
  scale_x_continuous(trans = "log") +
  ylim(0, 2.5) +
  labs(x = "Complejidad computacional", y = "MAE") +
  theme_bw() +
  theme(
        # X axis
        axis.title.x = element_text(margin = margin(15, 0, 0, 0)),
        axis.text.x = element_text(size = 12),
        # Y axis
        axis.title.y = element_text(margin = margin(0, 15, 0, 0)),
        axis.text.y = element_text(size = 12),
        # Panel
        panel.grid = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.background = element_rect(fill = "white")
    ) + 
    guides(colour = guide_legend(nrow = 1))
```
