# **K-nearest neighbors**

```{r}
pacman::p_load(tidyverse, tidymodels, timetk, here, kknn, tictoc, vip)
data <- read_csv(here("data", "main.csv")) %>% rename("date" = fecha)
```

## (a) Multiple forecasting horizons

### Forecast function

```{r}
k_nearest <-
  function(assess) {
    tic("KNN")
    
    # Training and testing partitions
    splits <- data %>% time_series_split(date, assess = assess, cumulative = TRUE)
    train <- training(splits)
    
    # Model specification
    knn <-
      nearest_neighbor(
        neighbors = tune(),
        weight_func = tune(),
        dist_power = tune()
      ) %>%
      set_engine("kknn") %>%
      set_mode("regression")
    
    # Feature engineering
    recipe <-
      train %>%
      recipe(ipc ~ .) %>%
      step_timeseries_signature(date) %>%
      step_rm(
        contains("am.pm"), contains("hour"), contains("minute"),
        contains("second"), contains("xts"), date_month.lbl, date_day,
        date_wday.lbl, date_mday, date_mday7
      )
    
    # Workflow
    workflow <- workflow() %>% add_model(knn) %>% add_recipe(recipe)
    
    # Hyperparameter tuning
    resamples <-
      train %>%
      rolling_origin(
        initial = (8 * 12),
        assess = (2 * 12),
        skip = 10,
        cumulative = TRUE
      )
    
    grid <-
      grid_latin_hypercube(neighbors(),
                           weight_func(),
                           dist_power(),
                           size = 15)
    
    metrics <- metric_set(mae, mase)
    
    doParallel::registerDoParallel()
    
    set.seed(123)
    tune <- 
      tune_grid(
        workflow,
        resamples = resamples,
        grid = grid,
        metrics = metrics,
        control = control_grid(save_pred = TRUE)
      )
    
    best_mae <- select_best(tune, "mae")
    
    # Final workflow
    final_workflow <-
      finalize_workflow(workflow,
                        best_mae)
    
    # Final model
    model <- last_fit(final_workflow, splits, metrics = metrics)
    metrics <- collect_metrics(model)
    
    # Forecast
    forecast <- model %>% collect_predictions() %>% select(.pred, .row, ipc)
    
    # Time elapsed
    toc(log = TRUE)
    time <- tic.log(format = TRUE)
    tic.clearlog()
    
    # Collect results
    results <- list(forecast, metrics, time)
    return(results)
  }
```

### Forecast horizons

```{r}
knn_3 <- k_nearest("3 months")

knn_3[[1]] %>% write_csv(here("results", "knn_3_forecast.csv"))
knn_3[[2]] %>% write_csv(here("results", "knn_3_metrics.csv"))
knn_3[[3]][[1]] %>% as_tibble() %>% write_csv(here("results", "knn_3_time.csv"))
```

```{r}
knn_9 <- k_nearest("9 months")

knn_9[[1]] %>% write_csv(here("results", "knn_9_forecast.csv"))
knn_9[[2]] %>% write_csv(here("results", "knn_9_metrics.csv"))
knn_9[[3]][[1]] %>% as_tibble() %>% write_csv(here("results", "knn_9_time.csv"))
```

```{r}
knn_12 <- k_nearest("12 months")

knn_12[[1]] %>% write_csv(here("results", "knn_12_forecast.csv"))
knn_12[[2]] %>% write_csv(here("results", "knn_12_metrics.csv"))
knn_12[[3]][[1]] %>% as_tibble() %>% write_csv(here("results", "knn_12_time.csv"))
```

```{r}
knn_24 <- k_nearest("24 months")

knn_24[[1]] %>% write_csv(here("results", "knn_24_forecast.csv"))
knn_24[[2]] %>% write_csv(here("results", "knn_24_metrics.csv"))
knn_24[[3]][[1]] %>% as_tibble() %>% write_csv(here("results", "knn_24_time.csv"))
```

### Safety checks

```{r}
knn_12[[1]] %>% 
  pivot_longer(-.row) %>% 
  ggplot(aes(.row, value, color = name)) +
  geom_line()
```

## (b) Model construction

### Train and test sets

```{r}
splits <- data %>% time_series_split(date, assess = "24 months", cumulative = TRUE)
train <- training(splits)
```

### Model specification

```{r}
knn <-
  nearest_neighbor(neighbors = tune(),
                   weight_func = tune(),
                   dist_power = tune()) %>%
  set_engine("kknn") %>% 
  set_mode("regression")
```

### Feature engineering

```{r}
recipe <- 
  train %>% 
  recipe(ipc ~ .)  %>%
  step_timeseries_signature(date) %>% 
  step_rm(contains("am.pm"), contains("hour"), contains("minute"),
          contains("second"), contains("xts"), date_month.lbl,
          date_day, date_wday.lbl, date_mday, date_mday7)
```

```{r}
recipe %>% prep() %>% juice() %>% glimpse
```

### Workflow

```{r}
workflow <- 
  workflow() %>% 
  add_model(knn) %>% 
  add_recipe(recipe)
```

### Hyperparameter tuning

```{r}
resamples <- 
  train %>% 
  rolling_origin(
    initial = 8 * 12,
    assess = 2 * 12,
    skip = 10,
    cumulative = TRUE)
```

```{r}
resamples %>%
  tk_time_series_cv_plan() %>%
  plot_time_series_cv_plan(date, ipc, 
                           .facet_ncol = 2, .interactive = F)
```

```{r}
grid <- 
  grid_latin_hypercube(
    neighbors(),
    weight_func(),
    dist_power(),
    size = 15
)
```

```{r}
doParallel::registerDoParallel()

metrics <- metric_set(mae, mase)

tic("KNN")

set.seed(123)
tune <- tune_grid(
  workflow,
  resamples = resamples,
  grid = grid,
  metrics = metrics,
  control = control_grid(save_pred = TRUE)
)

toc(log = TRUE)
time <- tic.log(format = TRUE)
tic.clearlog()
```

```{r}
tune %>% collect_metrics() %>% print(n = Inf)
best_mae <- select_best(tune, "mae"); best_mae
```

```{r}
tune %>%
  collect_metrics() %>%
  filter(.metric == "mae") %>%
  select(mean, neighbors, dist_power) %>%
  pivot_longer(c(neighbors, dist_power),
               values_to = "value",
               names_to = "parameter"
  ) %>%
  ggplot(aes(value, mean, color = parameter)) +
  geom_point(alpha = 0.8, show.legend = FALSE) +
  facet_wrap(~parameter, scales = "free_x") +
  labs(x = NULL, y = "MAE")
```

### Final model

```{r}
final <- 
  finalize_workflow(
  workflow,
  best_mae
)
```

```{r}
final_res <- last_fit(final, splits, metrics = metrics)
collect_metrics(final_res)
```

### Forecast

```{r}
final_res %>%
  collect_predictions() %>% 
  select(.pred, .row, ipc) %>% 
  pivot_longer(-.row) %>% 
  ggplot(aes(.row, value, color = name)) +
  geom_line()
```
