# Vector autoregression

```{r}
pacman::p_load(tidyverse, tidymodels, magrittr, here, vars, forecast, tseries, tictoc)
data <- read_csv(here("data", "main.csv")) %>% rename("date" = fecha)
```

## (a) Forecast function

```{r}
var <- function(last, lag, horizon) {
  
  last <- enquo(last)
  
  diffs <- 
    data %>% 
    dplyr::select(date, m1) %>% 
    filter(between(date, as.Date("2005-01-01"), as.Date(!!last))) %>% 
    dplyr::select(-date) %>% 
    ts(start = c(2005, 01), frequency = 12) %>% 
    diff(lag = 12)
  
  vars <- 
    data %>% 
    filter(between(date, as.Date("2006-01-01"), as.Date(!!last))) %>% 
    dplyr::select(ipc, imae) %>% 
    ts(start = c(2006, 01), frequency = 12)
  
  train <- cbind(vars, diffs)
  colnames(train) <- c("ipc", "imae", "m1")
  
  test <- data %>% 
    rowid_to_column(".row") %>% 
    tail(horizon) %>% 
    dplyr::select(ipc, .row)
  
  tic("VAR")
  selection <- VARselect(train, lag.max = lag, type = "const")
  model <- VAR(train, p = selection$selection[[1]], 
               type = "const", season = NULL, exog = NULL)
  
  forecast <- 
    predict(model, n.ahead = horizon, ci = 0.95)[[1]]$ipc %>% 
    as_tibble() %>% 
    dplyr::select(".pred" = fcst) %>% 
    mutate(key = "var") %>% 
    rowid_to_column(".row")
  
  toc(log = TRUE)
  time <- tic.log(format = TRUE)
  tic.clearlog()

  mae <-
    forecast %>% 
    dplyr::select(.pred) %>% 
    bind_cols(test %>% dplyr::select(ipc)) %>% 
    rename("truth" = ipc, "estimate" = .pred) %>% 
    mae(truth = truth, estimate = estimate)
  
  mase <-
    forecast %>% 
    dplyr::select(.pred) %>% 
    bind_cols(test %>% dplyr::select(ipc)) %>% 
    rename("truth" = ipc, "estimate" = .pred) %>% 
    mase(truth = truth, estimate = estimate)
  
  metrics <- bind_rows(mae, mase)
  
  results <- list(forecast, metrics, time)
  return(results)
}
```

```{r}
var_3 <- var(last = "2021-09-01", lag = 24, horizon = 3)

var_3[[1]] %>% write_csv(here("results", "var_3_forecast.csv"))
var_3[[2]] %>% write_csv(here("results", "var_3_metrics.csv"))
var_3[[3]][[1]] %>% as_tibble() %>% write_csv(here("results", "var_3_time.csv"))
```

```{r}
var_9 <- var(last = "2021-03-01", lag = 24, horizon = 9)

var_9[[1]] %>% write_csv(here("results", "var_9_forecast.csv"))
var_9[[2]] %>% write_csv(here("results", "var_9_metrics.csv"))
var_9[[3]][[1]] %>% as_tibble() %>% write_csv(here("results", "var_9_time.csv"))
```

```{r}
var_12 <- var(last = "2020-12-01", lag = 24, horizon = 12)

var_12[[1]] %>% write_csv(here("results", "var_12_forecast.csv"))
var_12[[2]] %>% write_csv(here("results", "var_12_metrics.csv"))
var_12[[3]][[1]] %>% as_tibble() %>% write_csv(here("results", "var_12_time.csv"))
```

```{r}
var_24 <- var(last = "2019-12-01", lag = 24, horizon = 24)

var_24[[1]] %>% write_csv(here("results", "var_24_forecast.csv"))
var_24[[2]] %>% write_csv(here("results", "var_24_metrics.csv"))
var_24[[3]][[1]] %>% as_tibble() %>% write_csv(here("results", "var_24_time.csv"))
```

### Safety checks

```{r}
var_3[[1]] %>% 
  bind_cols(data %>% dplyr::select(ipc) %>% tail(3)) %>% 
  dplyr::select(-key) %>% 
  pivot_longer(-.row) %>% 
  ggplot(aes(.row, value, color = name)) +
  geom_line()
```

## (b) Model building

```{r}
diffs <- 
  data %>% 
  dplyr::select(date, m1) %>% 
  filter(between(date, as.Date("2005-01-01"), as.Date("2019-12-01"))) %>% 
  dplyr::select(-date) %>% 
  ts(start = c(2005, 01), frequency = 12) %>% 
  diff(lag = 12)
```

```{r}
vars <- 
  data %>% 
  filter(between(date, as.Date("2006-01-01"), as.Date("2019-12-01"))) %>% 
  dplyr::select(ipc, imae) %>% 
  ts(start = c(2006, 01), frequency = 12)

df <- cbind(vars, diffs)
colnames(df) <- c("ipc", "imae", "m1")
head(df)
```

```{r}
lag <- 24
selection <- VARselect(df, lag.max = lag, type = "const")
selection$selection[[1]]

model <- VAR(df, p = selection$selection[[1]], type = "const", season = NULL, exog = NULL)
summary(model)
```

```{r}
serial.test(model, lags.pt = lag, type = "PT.asymptotic") # > 0.05
arch.test(model, lags.multi = lag, multivariate.only = TRUE) # < 0.05
normality.test(model, multivariate.only = TRUE) # > 0.05
```

```{r}
irf(model, impulse = "m1", response = "ipc", n.ahead = lag, boot = TRUE) %>% plot()
irf(model, impulse = "ipc", response = "m1", n.ahead = lag, boot = TRUE) %>% plot()
```

```{r}
par(mar = rep(2,4))
fevd(model, n.ahead = lag) %>% plot()
```

```{r}
par(mar = rep(2,4))
prediction <- predict(model, n.ahead = 24, ci = 0.95)[[1]]$ipc
prediction %>% fanchart()
```

```{r}
forecast <- prediction[[1]]$ipc
test <- data %>% rowid_to_column(".row") %>% tail(24) %>% dplyr::select(ipc, .row)

forecast %<>% 
  as_tibble() %>% 
  dplyr::select(".pred" = fcst) %>% 
  bind_cols(test)

forecast %>% 
  pivot_longer(-.row) %>% 
  ggplot(aes(.row, value, color = name)) +
  geom_line()

forecast %>% 
  rename("truth" = ipc, "estimate" = .pred) %>% 
    mae(truth = truth, estimate = estimate)
```
