# General data wrangling

```{r}
pacman::p_load(tidyverse, magrittr, janitor, here, readxl)
```

## Secmca

### Import/cleaning function

```{r}
import_secmca <- function(file, n = 5) {
  data <- 
    read_csv(here("data", "raw", "secmca", file)) %>% 
    slice(n:nrow(.)) %>% 
    row_to_names(1) %>% 
    clean_names() %>% 
    select(where(~!all(is.na(.x)))) %>% 
    rename("fecha" = na) %>% 
    separate(fecha, c("A", "B")) %>% 
    mutate(C = rep(1:12, length.out = nrow(.)),
           D = 1,
           fecha = str_c(A, C, D, sep = "-")) %>% 
    select(-c(A, B, C, D)) %>% 
    select(fecha, everything()) %>% 
    mutate(fecha = as.Date(fecha),
           across(where(is.character), as.double)) %>% 
    replace(is.na(.), 0)
}
```

### Import loop

```{r}
setwd(here("data", "raw", "secmca"))

filenames <- gsub("\\.csv$","", list.files(pattern = "\\.csv$"))

for(i in filenames){
  assign(i, import_secmca(paste(i, ".csv", sep = "")))
}

setwd(here())
```

### Variable selection

```{r}
exchange %<>% 
  select(fecha,
         "exchange" = tipo_de_cambio_de_compra_promedio_del_mes)

expec %<>% 
  select(fecha,
         "expec" = expectativas_de_inflacion)

imae %<>% 
  select(fecha,
         "imae" = imae_2) #tendencia-ciclo

ipc %<>% 
  select(fecha,
         "ipc" = ipc_variacion_interanual)

itcer %<>% 
  select(fecha,
         "itcer" = itcer_con_usa)

money %<>% 
  select(fecha,
         "m1" = agregado_monetario_m1,
         "m2" = agregado_monetario_m2)

rates %<>% 
  select(fecha,
         "deprate" = tasa_de_interes_pasiva_real_en_mn)

tpm %<>% 
  select(fecha,
         "tpm" = tasa_de_politica_monetaria)
```

### Dataset

```{r}
secmca <- 
  exchange %>% 
  inner_join(ipc) %>% 
  inner_join(rates) %>% 
  inner_join(itcer) %>% 
  inner_join(imae) %>% 
  inner_join(money) %>% 
  inner_join(tpm) %>% 
  inner_join(expec) %>% 
  write_csv(here("data", "raw", "secmca.csv"))
```

## Banguat

```{r}
cred <- 
  read_xls(here("data", "raw", "banguat", "cred.xls")) %>% 
  slice(3:15) %>%
  select(2:29) %>% 
  row_to_names(1) %>% 
  clean_names() %>% 
  mutate(mes = seq(1:12),
         across(where(is.character), as.double)) %>%
  pivot_longer(!mes, names_to = "año", values_to = "cred") %>% 
  mutate(año = as.double(str_remove_all(año, "x"))) %>% 
  arrange(año, mes) %>% 
  mutate(fecha = as.Date(str_c(año, mes, "1", sep = "-")),
         cred = round(cred, 2)) %>% 
  select(fecha, cred)

gov <- 
  read_xls(here("data", "raw", "banguat", "gov.xls")) %>% 
  slice(5:17) %>%
  select(1:28) %>% 
  row_to_names(1) %>% 
  clean_names() %>% 
  mutate(na = seq(1:12),
         across(where(is.character), as.double)) %>%
  pivot_longer(!na, names_to = "año", values_to = "gov") %>% 
  mutate(año = as.double(str_remove_all(año, "x"))) %>% 
  arrange(año, na) %>% 
  mutate(fecha = as.Date(str_c(año, na, "1", sep = "-")),
         gov = round(gov, 2)) %>% 
  select(fecha, gov)
```

```{r}
banguat <- cred %>% inner_join(gov) %>% write_csv(here("data", "raw", "banguat.csv"))
```

## Fred

```{r}
setwd(here("data", "raw", "fred"))

filenames <- gsub("\\.csv$","", list.files(pattern = "\\.csv$"))

for(i in filenames){
  assign(i, read_csv(paste(i, ".csv", sep = "")))
}

setwd(here())
```

```{r}
fred <- 
  cpi %>% 
  inner_join(oil) %>% 
  inner_join(sugar)

fred %>% 
  rename("fecha" = DATE,
         "cpi" = CPIAUCSL,
         "oil" = POILBREUSDM,
         "sugar" = PSUGAISAUSDM) %>% 
  mutate(across(where(is.numeric), ~round(.x, 4))) %>% 
  write_csv(here("data", "raw", "fred.csv"))
```
