# Feature selection

```{r}
pacman::p_load(tidyverse, magrittr, broom, lmtest, here)
```

### Import raw datasets

```{r}
secmca <- read_csv(here("data", "raw", "secmca.csv"))
banguat <- read_csv(here("data", "raw", "banguat.csv"))
fred <- read_csv(here("data", "raw", "fred.csv"))

selection <- secmca %>% inner_join(banguat) %>% inner_join(fred)
```

### Vectorized granger causality test

```{r}
granger_test <- function(data, x, y, lag) {
  x <- 
    data %>% 
    select(!!enquo(x)) %>% 
    pull() %>% 
    as.ts()
  
  y <- 
    data %>% 
    select(!!enquo(y)) %>% 
    pull() %>% 
    as.ts()
  
  grangertest(x, y, order = lag) %>% 
    tidy() %>% 
    select(3, 4) %>% 
    na.omit()
}

granger <- function(data, x, y, p_value) {
  list <- list()
  df <- data.frame()

  for (i in 1:24) {
    list <- granger_test(data, !!enquo(x), !!enquo(y), lag = i)
    df <- rbind(df, list) 
  } 
  
  df %<>% 
    rowid_to_column() %>% 
    filter(p.value < !!enquo(p_value)) %>% 
    arrange(p.value)
    
  return(df)
}
```

```{r}
names <- 
  selection %>% 
  select(-c(fecha, ipc_variacion_interanual)) %>%
  names() %>% 
  sort()
```

```{r}
lags <- list()

for (i in names) {
  lags[[i]] <- granger(selection, ipc_variacion_interanual, all_of(i), 0.05)
}

lags
```

### Feature selection

```{r}
main <- 
  selection %>% 
  select(
    fecha,
    "ipc" = ipc_variacion_interanual,
    "m1" = agregado_monetario_m1,
    "m0" = base_monetaria_restringida,
    "cpi" = consumer_price_index,
    "debt" = deuda_externa,
    "exports" = exportaciones_totales,
    "rev" = gobierno_ingresos,
    "hydro" = hidrocarburos_precio_promedio_de_importacion,
    "imae" = imae_variacion_interanual,
    "itcer" = itcer_global_variacion_interanual,
    "lendrate" = tasa_de_interes_activa_real_en_mn,
    "deprate" = tasa_de_interes_pasiva_nominal_en_mn,
    "tpm" = tasa_de_politica_monetaria,
    "bananas" = banano_precio_promedio_de_exportacion
  ) %>% 
  write_csv(here("data", "main.csv"))
```
