# General data wrangling

```{r}
pacman::p_load(tidyverse, magrittr, janitor, here)
```

## Secmca

### Import/cleaning function

```{r}
import_secmca <- function(file, n = 5) {
  data <- 
    read_csv(here("data", "raw", "secmca", file)) %>% 
    slice(n:nrow(.)) %>% 
    row_to_names(1) %>% 
    clean_names() %>% 
    select(where(~!all(is.na(.x)))) %>% 
    rename("fecha" = na) %>% 
    separate(fecha, c("A", "B")) %>% 
    mutate(C = rep(1:12, length.out = nrow(.)),
           D = 1,
           fecha = str_c(A, C, D, sep = "-")) %>% 
    select(-c(A, B, C, D)) %>% 
    select(fecha, everything()) %>% 
    mutate(fecha = as.Date(fecha),
           across(where(is.character), as.double)) %>% 
    replace(is.na(.), 0)
}
```

### Import loop

```{r}
setwd(here("data", "raw", "secmca"))

filenames <- gsub("\\.csv$","", list.files(pattern = "\\.csv$"))

for(i in filenames){
  assign(i, import_secmca(paste(i, ".csv", sep="")))
}

setwd(here())
```

### Variable selection

```{r}
exchange %<>% 
  select(fecha,
         "exchange" = tipo_de_cambio_de_compra_promedio_del_mes)

expec %<>% 
  select(fecha,
         "expec" = expectativas_de_inflacion)

imae %<>% 
  select(fecha,
         "imae" = imae_2) #tendencia-ciclo

ipc %<>% 
  select(fecha,
         "ipc" = ipc_variacion_interanual)

itcer %<>% 
  select(fecha,
         "itcer" = itcer_con_usa)

money %<>% 
  select(fecha,
         "m1" = agregado_monetario_m1,
         "m2" = agregado_monetario_m2)

rates %<>% 
  select(fecha,
         "deprate" = tasa_de_interes_pasiva_real_en_mn)

tpm %<>% 
  select(fecha,
         "tpm" = tasa_de_politica_monetaria)
```

### Dataset

```{r}
secmca <- 
  exchange %>% 
  inner_join(ipc) %>% 
  inner_join(rates) %>% 
  inner_join(itcer) %>% 
  inner_join(imae) %>% 
  inner_join(money) %>% 
  inner_join(tpm) %>% 
  inner_join(expec)
```

## Banguat

```{r}

```
