# Raw dataset

```{r}
pacman::p_load(tidyverse, magrittr, janitor, here, readxl)
```

## Secmca

### Import datasets

```{r}
secmca <- function(file, n = 5) {
  data <- 
    read_csv(here("data", "raw", "secmca", file)) %>% 
    slice(n:nrow(.)) %>% 
    row_to_names(1) %>% 
    clean_names() %>% 
    select(where(~!all(is.na(.x)))) %>% 
    rename("fecha" = na) %>% 
    separate(fecha, c("A", "B")) %>% 
    mutate(C = rep(1:12, length.out = nrow(.)),
           D = 1,
           fecha = str_c(A, C, D, sep = "-")) %>% 
    select(-c(A, B, C, D)) %>% 
    select(fecha, everything()) %>% 
    mutate(fecha = as.Date(fecha),
           across(where(is.character), as.double)) %>% 
    replace(is.na(.), 0)
}

setwd(here("data", "raw", "secmca"))
filenames <- gsub("\\.csv$","", list.files(pattern = "\\.csv$"))

for (i in filenames) {
  assign(i, secmca(paste(i, ".csv", sep = "")))
}

setwd(here())
```

### Interannual growth rate

```{r}
interannual <- function(data) {
  data %>% 
    mutate(across(where(is.numeric), ~ 100 * (log(.x) - lag(log(.x), 12)))) %>% 
    drop_na()
}

cred %<>% interannual()
exports_agri %<>% interannual()
exports %<>% interannual()
gov %<>% interannual()
imports_hidrocarbs %<>% interannual()
money_base %<>% interannual()
money %<>% interannual()

imae %<>% select(fecha, imae_variacion_interanual, imae_variacion_interanual_2)
ipc %<>% select(fecha, ipc_variacion_interanual)
pub_debt %<>% select(fecha, deuda_total_pib, deuda_interna_bruta_pib, deuda_externa_pib)
```

### Join and export

```{r}
secmca <- 
  exchange %>% 
  inner_join(ipc) %>% 
  inner_join(exports_agri) %>% 
  inner_join(pub_debt) %>% 
  inner_join(rates) %>% 
  inner_join(itcer) %>% 
  inner_join(imae) %>% 
  inner_join(money_base) %>% 
  inner_join(money) %>% 
  inner_join(cred) %>% 
  inner_join(exports) %>% 
  inner_join(tpm) %>% 
  inner_join(imports_hidrocarbs) %>% 
  filter(between(fecha, as.Date("2005-01-01"), as.Date("2021-12-01"))) %>% 
  write_csv(here("data", "raw", "secmca.csv"))
```

## Banguat

### Import datasets

```{r}
cred <- 
  read_xls(here("data", "raw", "banguat", "cred.xls")) %>% 
  slice(3:15) %>%
  select(2:29) %>% 
  row_to_names(1) %>% 
  clean_names() %>% 
  mutate(mes = seq(1:12),
         across(where(is.character), as.double)) %>%
  pivot_longer(!mes, names_to = "año", values_to = "credito_sector_privado") %>% 
  mutate(año = as.double(str_remove_all(año, "x"))) %>% 
  arrange(año, mes) %>% 
  mutate(fecha = as.Date(str_c(año, mes, "1", sep = "-")),
         credito_sector_privado = round(credito_sector_privado, 2)) %>% 
  select(fecha, credito_sector_privado)

gov_expend <- 
  read_xls(here("data", "raw", "banguat", "gov_expend.xls")) %>% 
  slice(5:17) %>%
  select(1:28) %>% 
  row_to_names(1) %>% 
  clean_names() %>% 
  mutate(na = seq(1:12),
         across(where(is.character), as.double)) %>%
  pivot_longer(!na, names_to = "año", values_to = "gobierno_gastos") %>% 
  mutate(año = as.double(str_remove_all(año, "x"))) %>% 
  arrange(año, na) %>% 
  mutate(fecha = as.Date(str_c(año, na, "1", sep = "-")),
         gobierno_gastos = round(gobierno_gastos, 2)) %>% 
  select(fecha, gobierno_gastos)

gov_rev <- 
  read_xls(here("data", "raw", "banguat", "gov_rev.xls")) %>% 
  slice(5:17) %>%
  select(1:28) %>% 
  row_to_names(1) %>% 
  clean_names() %>% 
  mutate(na = seq(1:12),
         across(where(is.character), as.double)) %>%
  pivot_longer(!na, names_to = "año", values_to = "gobierno_ingresos") %>% 
  mutate(año = as.double(str_remove_all(año, "x"))) %>% 
  arrange(año, na) %>% 
  mutate(fecha = as.Date(str_c(año, na, "1", sep = "-")),
         gobierno_ingresos = round(gobierno_ingresos, 2)) %>% 
  select(fecha, gobierno_ingresos)

debt_ext <- 
  read_xls(here("data", "raw", "banguat", "debt_ext.xls")) %>% 
  slice(4:16) %>%
  select(1:28) %>% 
  row_to_names(1) %>% 
  clean_names() %>% 
  mutate(mes = seq(1:12),
         across(where(is.character), as.double)) %>%
  pivot_longer(!mes, names_to = "año", values_to = "deuda_externa") %>% 
  mutate(año = as.double(str_remove_all(año, "x"))) %>% 
  arrange(año, mes) %>% 
  mutate(fecha = as.Date(str_c(año, mes, "1", sep = "-")),
         deuda_externa = round(deuda_externa, 2)) %>% 
  select(fecha, deuda_externa)

debt_int <- 
  read_xls(here("data", "raw", "banguat", "debt_int.xls")) %>% 
  slice(4:16) %>%
  select(1:28) %>% 
  row_to_names(1) %>% 
  clean_names() %>% 
  mutate(na = seq(1:12),
         across(where(is.character), as.double)) %>%
  pivot_longer(!na, names_to = "año", values_to = "deuda_interna") %>% 
  mutate(año = as.double(str_remove_all(año, "x"))) %>% 
  arrange(año, na) %>% 
  mutate(fecha = as.Date(str_c(año, na, "1", sep = "-")),
         deuda_interna = round(deuda_interna, 2)) %>% 
  select(fecha, deuda_interna)
```

### Interannual growth rate

```{r}
cred %<>% interannual()
gov_expend %<>% interannual()
gov_rev %<>% interannual()
debt_ext %<>% interannual()
debt_int %<>% interannual()
```

### Join and export

```{r}
banguat <- 
  cred %>% 
  inner_join(gov_expend) %>% 
  inner_join(gov_rev) %>% 
  inner_join(debt_ext) %>% 
  inner_join(debt_int) %>%  
  filter(between(fecha, as.Date("2005-01-01"), as.Date("2021-12-01"))) %>% 
  write_csv(here("data", "raw", "banguat.csv"))
```

## FRED

### Import dataset

```{r}
fred <- 
  read_csv(here("data", "raw", "fred", "cpi.csv")) %>% 
  rename("fecha" = DATE, 
         "consumer_price_index" = CPIAUCSL) %>% 
  interannual() %>% 
  filter(between(fecha, as.Date("2005-01-01"), as.Date("2021-12-01"))) %>% 
  write_csv(here("data", "raw", "fred.csv"))
```
